### ISSUE TITLE
是否支持加载图片列表？

### ISSUE THREAD

**Issue by water110** [ihmily/ComfyUI-Light-Tool#1]
官方自带的加载图像列表加载出来的透明底图片，会变成黑底，看到咱们这个节点中加载图片的有一个选项是保持alpha通道，可以实现加载透明底图片，但是没有找到加载图像列表的方法。

**Comment by ihmily** [comment]
你说的是官方哪个节点？可以贴一下图吗

**Comment by ihmily** [comment]
@water110 已新增加载图片列表节点，支持保持透明度

![image](https://github.com/user-attachments/assets/9fc62abd-5e15-422b-acfb-4f0a75c35643)
