### ISSUE TITLE
RGB2RGBA.__init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by iieoc** [ihmily/ComfyUI-Light-Tool#3]
I got this error message

# ComfyUI Error Report
## Error Details
- **Node Type:** Light-Tool: ImageMaskApply
- **Exception Type:** TypeError
- **Exception Message:** RGB2RGBA.__init__() takes 1 positional argument but 3 were given
## Stack Trace
```
  File "D:\comfyUI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\comfyUI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\comfyUI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\comfyUI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\comfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Light-Tool\nodes\light_tool.py", line 254, in run
    image_pil = RGB2RGBA(image_pil, mask_pil)

```
## System Information
- **ComfyUI Version:** v0.2.7

I am not a Python programmer, but I think RGB2RGBA may have been defined incorrectly.
Is it reasonable in Python that RGB2RGBA is a function in the light_tool_utils.py, but it is a class in the light_tool. py?

**Comment by ihmily** [comment]
yes, it is a bug. I have fixed it, you can fetch the latest code. thanks !

**Comment by iieoc** [comment]
Okay, thank you, my friend
